# M5 Atom S3
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Bluetooth Proxy
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms

bluetooth_proxy:
  active: true

# Online Status
binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected

# Uptime Sensor
sensor:
  - platform: uptime
    type: seconds
    update_interval: 30s
    name: Uptime Sensor

# Wifi Signal Strength
  - platform: wifi_signal
    name: "Wifi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy
    source_id: wifi_signal_db
    name: "Wifi Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

# Ip Address
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address

#Dashboard
web_server:
  port: 80
  version: 3

# Wake on Lan
button:
  - platform: wake_on_lan
    name: ${device1_name}
    target_mac_address: ${device1_mac}

  - platform: wake_on_lan
    name: ${device2_name}
    target_mac_address: ${device2_mac}
