# M5 Atom S3
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Presense Sensor
uart:
  id: UART2
  rx_pin: GPIO2
  tx_pin: GPIO3
  baud_rate: 256000
  data_bits: 8
  stop_bits: 1
  parity: NONE

ld2410:
  id: my_ld2410
  uart_id: UART2

# Online Status
binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected

# Presense Sensor
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

# Uptime Sensor
sensor:
  - platform: uptime
    type: seconds
    update_interval: 30s
    name: Uptime Sensor

# Presense Sensor
  - platform: ld2410
    moving_distance:
      name : Moving Distance
    moving_energy:
      name: Move Energy
    detection_distance:
      name: Detection Distance

# Presense Sensor
switch:
  - platform: ld2410
    bluetooth:
      name: "Bluetooth"

# Dashboard
web_server:
  port: 80
  version: 3# M5 Atom S3
substitutions:
  name: "presence"
  friendly_name: "Presence Sensor"
  room: "Office"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "/9WG77dF8m/ygggfnSHhQJ5Z3fNEU5spDJN4KuJD0bU="

# Over the Air Updates
ota:
- platform: esphome
  password: !secret ota_password

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Presense Sensor
uart:
  id: UART2
  rx_pin: GPIO2
  tx_pin: GPIO3
  baud_rate: 256000
  data_bits: 8
  stop_bits: 1
  parity: NONE

ld2410:
  id: my_ld2410
  uart_id: UART2

# Online Status
binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected

# Presense Sensor
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

# Uptime Sensor
sensor:
  - platform: uptime
    type: seconds
    update_interval: 30s
    name: Uptime Sensor

# Presense Sensor
  - platform: ld2410
    moving_distance:
      name : Moving Distance
    moving_energy:
      name: Move Energy
    detection_distance:
      name: Detection Distance

# Presense Sensor
switch:
  - platform: ld2410
    bluetooth:
      name: "Bluetooth"

# Dashboard
web_server:
  port: 80
  version: 3
