# Designed for M5AtomS3
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}
  includes:
    - ld2412.h

# Enable logging
logger:

# Bluetooth Tracker
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms

#Bluetooth Proxy
bluetooth_proxy:
  active: true

# Presense Sensor
uart:
  id: uart_1
  rx_pin: GPIO1
  tx_pin: GPIO2
  baud_rate: 115200
  parity: NONE

# Presense Sensor
custom_component:
  - lambda: |-
      return {new LD2412(id(uart_1))};
    components:
      - id: ld2412

binary_sensor:
# Presense Sensor
  - platform: custom
    lambda: |-
      auto uart_component = static_cast<LD2412 *>(ld2412);
      return {uart_component->hasTarget,uart_component->hasMovingTarget,uart_component->hasStillTarget};
    binary_sensors:
      - name: "Has Target"
      - name: "Has Moving Target"
      - name: "Has Still Target"

# Online Status
  - platform: status
    name: "Online"
    id: ink_ha_connected
    icon: mdi:check-network

sensor: 
# Presense Sensor
  - platform: custom
    lambda: |-
      auto uart_component = static_cast<LD2412 *>(ld2412);
      return {uart_component->movingTargetDistance,uart_component->movingTargetEnergy,uart_component->stillTargetDistance,uart_component->stillTargetEnergy};
    sensors:
      - name: "Moving Target Distance"
        unit_of_measurement: "cm"
        accuracy_decimals: 0
      - name: "Moving Target Energy"
        unit_of_measurement: "%"
        accuracy_decimals: 0
      - name: "Still Target Distance"
        unit_of_measurement: "cm"
        accuracy_decimals: 0
      - name: "Still Target Energy"
        unit_of_measurement: "%"
        accuracy_decimals: 0

# Uptime Sensor
  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    entity_category: diagnostic
    internal: true

# Wifi Signal Strength
  - platform: wifi_signal
    name: "Wifi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    internal: true

# Wifi Signal Strength
  - platform: copy
    source_id: wifi_signal_db
    name: "Wifi Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    icon: mdi:wifi
    entity_category: "diagnostic"
    device_class: ""

text_sensor:
# Ip Address
  - platform: wifi_info
    ip_address:
      name: IP Address
      icon: mdi:ip-network

# Uptime Sensor
  - platform: template
    name: "Uptime"
    id: uptimes
    icon: mdi:update
    entity_category: diagnostic
    lambda: |-
      int seconds = (id(uptime_sensor).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      if ( days > 3650 ) {
        return { "Starting up" };
      } else if ( days ) {
        return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else if ( hours ) {
        return { (String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else if ( minutes ) {
        return { (String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else {
        return { (String(seconds) +"s").c_str() };
      }

button:
# Presense Sensor  
  - platform: template
    name: "Reboot sensor"
    on_press:
      lambda: 'static_cast<LD2412 *>(ld2412)->reboot();'

#Dashboard
web_server:
  port: 80
  version: 3
