# Screens
substitutions:
  screen_main: "master"
  screen_rooms: "rooms"
  screen_kitchen: "sliders"
  screen_led: "led"


# Brightness Control
number:
  - platform: template
    id: screen_brightness
    name: Active screen brightness
    min_value: 0
    max_value: 100
    step: 5
    initial_value: 75
    restore_value: true
    set_action:
      - lambda: |-
          if (!id(deck).get_inactivity())
            id(device).set_brightness(x);

  - platform: template
    id: inactive_screen_brightness
    name: Inactive screen brightness
    min_value: 0
    max_value: 100
    step: 5
    initial_value: 20
    restore_value: true
    set_action:
      - lambda: |-
          if (id(deck).get_inactivity())
            id(device).set_brightness(x);


# Dummy Light
light:
  - platform: monochromatic
    id: dummy_light
    name: Dummy
    output: out_10




  screens:

# Main Screen
    - name: ${screen_main}
      widgets:
        - type: value-card
          id: local_time
          position: 8, 8
          dimensions: 228x96
          text: "London (England)"
          enabled: return true;
          on_click:
            - logger.log: "Time clicked"

        - type: button
          position: 8, 216
          text: Dummy
          icon: 󰝩
          toggle: true
          enabled: return true;
 #         checked: |-
 #           return id(dummy_light).current_values.is_on();
          on_turn_on:
            - homeassistant.service:
                service: light.turn_on
                data:
                  entity_id: light.office_lamp_light
          on_turn_off:
            - homeassistant.service:
                service: light.turn_off
                data:
                  entity_id: light.office_lamp_light
