substitutions:
  SCREEN_BLINDS: blinds

sensor:
# Office Blinds
  - platform: homeassistant
    id: office_blind_position
    entity_id: cover.office_blind
    attribute: target_lift_position


# Main Screen
  screens:
    - name: ${SCREEN_MAIN}
      widgets:

        # Blinds Open Page
        - type: button
          position: 126, 216
          text: Blind
          icon: 󰂬
          enabled: return true;
          checked: |-
            return id(office_blind).state;
          on_click:
            lambda: id(deck).switch_screen("$SCREEN_BLINDS");


# Slider for Blinds
    - name: ${SCREEN_BLINDS}
      widgets:

        - type: button
          position: 0, 0
          dimensions: 48x320
          icon: 󰅁
          enabled: return true;
          on_click:
            - lambda: id(deck).switch_screen("$SCREEN_MAIN");

        - type: slider
          position: 200, 8
          dimensions: 100x304
          text: Blind
          min: 0
          max: 100
          enabled: return true;
          value: return id(office_blind_position).state;
          on_change:
          - homeassistant.service:
              service: cover.set_cover_position
              data:
                entity_id: cover.office_blind
                position: !lambda return x;
