# M5Stack Atom S3 with illuminance and environment sensors
substitutions:
  name: "48a8"
  friendly_name: "Echo (48a8)"
  room: "Home"
  project: "M5stack.Echo"
  version: "2025.06"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/jtenniswood/esphome/
    files: [base/m5-echo.yaml,
            addon/echo.yaml,
            addon/network.yaml,
            addon/webserver.yaml]
    refresh: 1sec