# M5 Nano C6 with illuminance and environment sensors
substitutions:
  name: "0000"
  friendly_name: "Sensor (0000)"
  project: "Seeed Studio.Xiao C6"
  version: "2025"
  room_id1: "Room 1" #"living_room_device"
  room_name1: "Room 1" #"Living Room Sensors"
  area_id1: "Area 1" #"living_room_area"
  room_id2: "Room 2" #"bedroom_device"
  room_name2: "Room 2" #"Bedroom Sensors"
  area_id2: "Area 2" #"bedroom_area"
  update_interval: "1s" #60s when stable
  temperature_sht40_room: "${room_id1}"
  humidity_sht40_room: "${room_id1}"
  pressure_bmp280_room: "${room_id1}"
  gr2_ace_vpd_room: "${room_id1}"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/jtenniswood/esphome/
    files: [base/m5-nano-multi-room.yaml,
            interface/i2c-nano.yaml,
            addon/bluetooth.yaml,
            addon/illuminance.yaml,
            addon/environment-multi-room.yaml,
            addon/network.yaml,
            addon/webserver.yaml]
    refresh: 1sec