# M5Stack Nano C6 with motion sensor
substitutions:
  name: "0000"
  friendly_name: "Room Sensor (0000)"
  room: "Room"
  project: "Seeed Studio.Xiao C6"
  version: "2025"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/jtenniswood/esphome/
    files: [base/m5-nano.yaml,
            addon/motion.yaml,
            addon/network.yaml,
            addon/webserver.yaml]
    refresh: 1sec