# Xiao C6 with Xiao Mmwave Sensor
substitutions:
  name: "0000"
  friendly_name: "Room Sensor (0000)"
  room: "Room"

# Presence Sensor
  rx_pin: "GPIO2"
  tx_pin: "GPIO21"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/jtenniswood/esphome/
    files: [base/xiao-c6.yaml,
            addon/bluetooth.yaml,
            addon/presence.yaml,
            addon/network.yaml,
            addon/webserver.yaml]
    refresh: 1sec