# M5 Nano C6
substitutions:
  name: "test-device"
  friendly_name: "Test Device"
  room: "Office"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/jtenniswood/esphome/
    files: [base/m5-nano.yaml,
            addon/illuminance.yaml]
    refresh: 1sec