
# I2S Audio configuration for microphone and speaker
i2s_audio:
  i2s_lrclk_pin: GPIO33
  i2s_bclk_pin: GPIO19

# Microphone configuration
microphone:
  - platform: i2s_audio
    id: atom_echo_microphone
    i2s_din_pin: GPIO23
    adc_type: external
    pdm: true

# Speaker configuration  
speaker:
  - platform: i2s_audio
    id: atom_echo_speaker
    i2s_dout_pin: GPIO22
    dac_type: external
    i2s_mode: primary

# Voice Assistant (requires Home Assistant)
voice_assistant:
  microphone: atom_echo_microphone
  speaker: atom_echo_speaker
  noise_suppression_level: 2
  auto_gain: 31dBFS
  volume_multiplier: 2.0
  
  on_listening:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        effect: "Slow Pulse"
        
  on_stt_vad_end:
    - light.turn_on:
        id: led
        blue: 0%
        red: 100%
        green: 0%
        effect: "Fast Pulse"
        
  on_tts_start:
    - light.turn_on:
        id: led
        blue: 0%
        red: 0%
        green: 100%
        brightness: 100%
        effect: none
        
  on_end:
    - delay: 100ms
    - light.turn_off: led
    - script.execute: reset_led
        
  on_error:
    - light.turn_on:
        id: led
        red: 100%
        green: 0%
        blue: 0%
        brightness: 100%
        effect: none
    - delay: 1s
    - script.execute: reset_led

# LED Strip (WS2812B)
light:
  - platform: esp32_rmt_led_strip
    id: led
    name: "LED"
    pin: GPIO27
    num_leds: 1
    rgb_order: GRB
    chipset: ws2812
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%

# Button
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: "Button"
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - if:
              condition:
                switch.is_on: use_wake_word
              then:
                - voice_assistant.start:
              else:
                - voice_assistant.start_continuous:
      - timing:
          - ON for at least 4s
        then:
          - button.press: factory_reset_btn

# Wake word detection (optional)
switch:
  - platform: template
    name: "Use Wake Word"
    id: use_wake_word
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON

# Factory reset button
button:
  - platform: factory_reset
    name: "Factory Reset"
    id: factory_reset_btn

# Script to reset LED to default state
script:
  - id: reset_led
    then:
      - if:
          condition:
            switch.is_on: use_wake_word
          then:
            - light.turn_on:
                id: led
                red: 100%
                green: 89%
                blue: 71%
                brightness: 60%
                effect: none
          else:
            - light.turn_off: led