# Data Bus
i2c:
  - id: bus_a
    sda: 2
    scl: 1
    scan: true


sensor:
# Temperature and Humidity Sensor
  - platform: sht4x
    temperature:
      name: "SHT40 Temperature"
    humidity:
      name: "SHT40 Relative Humidity"
    address: 0x44

# Temperature and Pressure Sensor
  - platform: bmp280_i2c
    address: 0x76
    temperature:
      name: "BMP280 Temperature"
    pressure:
      name: "BMP280 Pressure"