# Data Bus
i2c:
  - id: bus_illuminance
    sda: 1  # G1 pin (White)
    scl: 2  # G2 pin (Yellow)
    scan: true
    frequency: 100kHz  # Lower frequency for better reliability

# Enable logging for I2C
logger:
  level: VERY_VERBOSE
  logs:
    sensor: DEBUG
    i2c: DEBUG

sensor:    
# Illuminance Sensor
  - platform: bh1750
    name: "Sensor"
    address: 0x23
    update_interval: 1s
    id: illuminance_sensor
