# M5 Atom compatible

# Data Bus
i2c:
  - id: bus_a
    sda: 2
    scl: 1
    scan: true

# Data Bus
# i2c:
#   - id: bus_a
#     sda: {sda_pin}
#     scl: {scl_pin}
#     scan: true

sensor:    
# Illuminance Sensor
  - platform: bh1750
    name: "Sensor"
    address: 0x23
    update_interval: 1s