# PIR Motion Sensor
binary_sensor:
  - platform: gpio
    pin: GPIO1
    name: "PIR Motion Sensor"
    device_class: motion
    filters:
      - delayed_off: 2s  # Account for the 2-second delay mentioned in specs