# PIR Motion Sensor
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO2
      mode:
        input: true
        pullup: false
    name: "Motion Sensor"
    device_class: motion
#    filters:
#      - delayed_on: 10ms
#      - delayed_off: 2s