# PIR Motion Sensor
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO2
      inverted: true
      mode:
        input: true
        pullup: false
        pulldown: true
    name: "PIR Sensor1"
    id: pir_sensor1
    device_class: motion
    filters:
      - delayed_on: 10ms
      - delayed_off: 2s