# Online Status
binary_sensor:
  - platform: status
    name: "Online"
    id: ink_ha_connected
    icon: mdi:check-network

sensor:
# Uptime
  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    entity_category: diagnostic
    internal: true
