# LD2410 Presense Sensor
uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: 10
  tx_pin: 9
  parity: NONE
  stop_bits: 1


# Presense Sensor
ld2410:
  id: my_ld2410
  uart_id: uart_bus


# Online Status
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
      id: has_target
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
      

sensor:
# Presense Sensor
  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
      id: detection_distance


# Presense Sensor
switch:
  - platform: ld2410
    bluetooth:
      name: "Bluetooth"
