# ld2412 Presense Sensor
external_components:
  - source:
      type: git
      url: https://github.com/screekworkshop/custom_components_support_for_screek_l12
      ref: main
    components: [ld2412]

uart:
  id: uart_bus
  tx_pin: 
    number: GPIO${tx_pin}
    mode:
      input: true
      pullup: true
  rx_pin: 
    number: GPIO${rx_pin}
    mode:
      input: true
      pullup: true
  baud_rate: 115200
  parity: NONE
  stop_bits: 1
  data_bits: 8

ld2412:
  id: ld2412_radar

binary_sensor:
  - platform: ld2412
    has_target:
      name: Presence
      id: has_target
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

sensor:
  - platform: ld2412
    moving_distance:
      name : Moving Distance
      id: moving_distance
    still_distance:
      name: Still Distance
      id: still_distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    luminance:
      name: luminance

time:
  - platform: sntp
    id: time_now

button:
  - platform: template
    name: "LD2412 BLE Enable"
    # disabled_by_default: True
    entity_category: "config"
    icon: mdi:bluetooth
    on_press:
      lambda: |-
        id(ld2412_radar) -> ble_control(true);
  - platform: template
    name: "LD2412 BLE Disable"
    # disabled_by_default: True
    entity_category: "config"
    icon: mdi:bluetooth-off
    on_press:
      lambda: |-
        id(ld2412_radar) -> ble_control(false);
  - platform: template
    name: "LD2412 Reboot"
    icon: mdi:radar
    entity_category: "config"
    on_press:
      lambda: |-
        id(ld2412_radar) -> reboot();
  - platform: template
    name: "LD2412 Factory Reset"
    icon: mdi:restart
    entity_category: "config"
    on_press:
      - lambda: |-
          id(ld2412_radar) -> factoryReset();

number:
  - platform: ld2410
    g0:
      move_threshold:
        name: "G0 Move Threshold"
      still_threshold:
        name: "G0 Still Threshold"
    g1:
      move_threshold:
        name: G1 Move Threshold
      still_threshold:
        name: G1 Still Threshold
    g2:
      move_threshold:
        name: G2 Move Threshold
      still_threshold:
        name: G2 Still Threshold
    g3:
      move_threshold:
        name: G3 Move Threshold
      still_threshold:
        name: G3 Still Threshold
    g4:
      move_threshold:
        name: G4 Move Threshold
      still_threshold:
        name: G4 Still Threshold
    g5:
      move_threshold:
        name: G5 Move Threshold
      still_threshold:
        name: G5 Still Threshold
    g6:
      move_threshold:
        name: G6 Move Threshold
      still_threshold:
        name: G6 Still Threshold
    g7:
      move_threshold:
        name: G7 Move Threshold
      still_threshold:
        name: G7 Still Threshold
    g8:
      move_threshold:
        name: G8 Move Threshold
      still_threshold:
        name: G8 Still Threshold