# Sensor Library
esphome:
  includes:
    - library/ld2412.h


# Presense Sensor
uart:
  id: uart_1
  rx_pin: GPIO1
  tx_pin: GPIO2
  baud_rate: 115200
  parity: NONE


# Presense Sensor
custom_component:
  - lambda: |-
      return {new LD2412(id(uart_1))};
    components:
      - id: ld2412


binary_sensor:
# Presense Sensor
  - platform: custom
    lambda: |-
      auto uart_component = static_cast<LD2412 *>(ld2412);
      return {uart_component->hasTarget,uart_component->hasMovingTarget,uart_component->hasStillTarget};
    binary_sensors:
      - name: "Presence"
        icon: mdi:account
      - name: "Moving Target"
        icon: mdi:motion-sensor
      - name: "Still Target"
        icon: mdi:motion-sensor


sensor: 
# Presense Sensor
  - platform: custom
    lambda: |-
      auto uart_component = static_cast<LD2412 *>(ld2412);
      return {uart_component->movingTargetDistance,uart_component->movingTargetEnergy,uart_component->stillTargetDistance,uart_component->stillTargetEnergy};
    sensors:
      - name: "Moving Distance"
        unit_of_measurement: "cm"
        accuracy_decimals: 0
        icon: mdi:signal-distance-variant
      - name: "Moving Energy"
        unit_of_measurement: "%"
        accuracy_decimals: 0
        icon: mdi:motion-sensor
      - name: "Still Distance"
        unit_of_measurement: "cm"
        accuracy_decimals: 0
        icon: mdi:signal-distance-variant
      - name: "Still Energy"
        unit_of_measurement: "%"
        accuracy_decimals: 0
        icon: mdi:flash


# Presense Sensor 
button: 
  - platform: template
    name: "Reboot sensor"
    on_press:
      lambda: 'static_cast<LD2412 *>(ld2412)->reboot();'


# Presense Sensor
switch:
  - platform: ld2412
    bluetooth:
      name: "Bluetooth"
