number:
# Zone 1
  - platform: template
    name: "${zone1} Zone End"
    id: presence_z1_end
    device_class: distance
    min_value: 0
    max_value: 600
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 10
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG

  # Zone 2
  - platform: template
    name: "${zone2} Zone End"
    id: presence_z2_end
    device_class: distance
    min_value: 0
    max_value: 600
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 36
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG

binary_sensor:
  ## Presence zones
  - platform: template
    name: "${zone1} Occupancy"
    device_class: occupancy
    icon: mdi:motion-sensor
    lambda: |-
      if ((id(has_target).state) && (id(detection_distance).state < id(presence_z1_end).state)) {
        return true;
      } else {
        return false;
      }
  - platform: template
    name: "${zone2} Occupancy"
    device_class: occupancy
    icon: mdi:motion-sensor
    lambda: |-
      if ((id(has_target).state) && ((id(presence_z1_end).state < id(detection_distance).state) && (id(detection_distance).state < id(presence_z2_end).state))) {
        return true;
      } else {
        return false;
      }
