# Presense Sensor
uart:
  id: UART2
  rx_pin: GPIO1
  tx_pin: GPIO2
  baud_rate: 256000
  data_bits: 8
  stop_bits: 1
  parity: NONE

# Presense Sensor
ld2410:
  id: my_ld2410
  uart_id: UART2

# Online Status
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
      id: has_target
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
      

sensor:
# Presense Sensor
  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
      id: detection_distance

# Presense Sensor
switch:
  - platform: ld2410
    bluetooth:
      name: "Bluetooth"
