# Sensor Library
esphome:
  includes:
    - library/ld2412.h


# Presense Sensor
uart:
  id: uart_1
  rx_pin: GPIO1
  tx_pin: GPIO2
  baud_rate: 115200
  parity: NONE


# Presense Sensor
custom_component:
  - lambda: |-
      return {new LD2412(id(uart_1))};
    components:
      - id: ld2412


binary_sensor:
# Presense Sensor
  - platform: custom
    lambda: |-
      auto uart_component = static_cast<LD2412 *>(ld2412);
      return {uart_component->hasTarget,uart_component->hasMovingTarget,uart_component->hasStillTarget};
    binary_sensors:
      - name: "Has Target"
      - name: "Has Moving Target"
      - name: "Has Still Target"


sensor: 
# Presense Sensor
  - platform: custom
    lambda: |-
      auto uart_component = static_cast<LD2412 *>(ld2412);
      return {uart_component->movingTargetDistance,uart_component->movingTargetEnergy,uart_component->stillTargetDistance,uart_component->stillTargetEnergy};
    sensors:
      - name: "Moving Target Distance"
        unit_of_measurement: "cm"
        accuracy_decimals: 0
      - name: "Moving Target Energy"
        unit_of_measurement: "%"
        accuracy_decimals: 0
      - name: "Still Target Distance"
        unit_of_measurement: "cm"
        accuracy_decimals: 0
      - name: "Still Target Energy"
        unit_of_measurement: "%"
        accuracy_decimals: 0


button:
# Presense Sensor  
  - platform: template
    name: "Reboot sensor"
    on_press:
      lambda: 'static_cast<LD2412 *>(ld2412)->reboot();'
