# Designed for M5AtomS3
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}
  project:
    name: ${project}
    version: ${version}

# Over the Air Updates
ota:
- platform: esphome

# Enable Home Assistant API
api:

# Enable logging
logger:
