# Designed for M5NanoC6
esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.1.2
    platform_version: 6.5.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      CONFIG_OPENTHREAD_ENABLED: n #
      CONFIG_ENABLE_WIFI_STATION: y #
      CONFIG_USE_MINIMAL_MDNS: y #

# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}

# Over the Air Updates
ota:
- platform: esphome

# Enable Home Assistant API
api:

# Enable logging
logger:

light:
  # Status Light
  - platform: status_led
    name: "Status LED"
    entity_category: diagnostic
    pin: GPIO7

  # Led Light
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO20
    num_leds: 4
    rmt_channel: 1
    chipset: ws2812
    name: "Led Light"
    entity_category: diagnostic
    power_supply: rgbpwr

# Led Power
power_supply:
  - id: 'rgbpwr'
    enable_on_boot: true
    pin: GPIO19
    enable_time: 10ms
    keep_on_time: 10ms

# Button
binary_sensor:
  - platform: gpio
    name: Button
    pin:
      number: GPIO9
      inverted: true
      mode:
        input: true
        pullup: true
      # ignore_strapping_warning: true
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log: Button Pressed