# Designed for M5NanoC6
esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}
  project:
    name: ${project}
    version: ${version}

# Over the Air Updates
ota:
- platform: esphome

# Enable Home Assistant API
api:

# Enable logging
logger: