# Designed for M5NanoC6
esp32:
  board: esp32-c6-devkitc-1    # use the devkit configuration which is compatible with the Nano C6
  flash_size: 4MB             # Nano C6 typically comes with 4MB flash (adjust if yours has 8MB)
  variant: esp32c6
  framework:
    type: esp-idf
#    version: 5.3.1
#    platform_version: 6.9.0
#    sdkconfig_options:
#      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}

# Over the Air Updates
ota:
- platform: esphome

# Enable Home Assistant API
api:

# Enable logging
logger: