# Designed for M5AtomS3
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}

# Enable logging
logger:

#Dashboard
web_server:
  port: 80
  version: 3
