# Designed for M5AtomS3
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}

# Enable logging
logger:

# Esphome version sensor
text_sensor:
  - platform: version
    name: Version
    icon: mdi:package-variant-closed
    hide_timestamp: true
