# Designed for WT32-SC01 PLUS
#esp32:
#  board: esp32-s3-devkitc-1
#  framework:
#    type: arduino
  flash_size: 16MB

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y



# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}
  platformio_options:
    board_upload.maximum_ram_size: 327680
    board_upload.maximum_size: 16777216

# Over the Air Updates
ota:
- platform: esphome

# Enable Home Assistant API
api:

# Enable logging
logger:

# Packages
external_components:
  - source:
      type: git
      url: https://github.com/strange-v/ha_deck
      ref: main
    components: [ hd_device_sc01_plus, ha_deck ]

# Screen Brightness
hd_device_sc01_plus:
  id: device
  brightness: 100
