# Designed for WT32-SC01 PLUS
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
  flash_size: 16MB

# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}
  platformio_options:
    board_upload.maximum_ram_size: 327680
    board_upload.maximum_size: 16777216

# Over the Air Updates
ota:
- platform: esphome

# Enable Home Assistant API
api:

# Enable logging
logger:

# Packages
external_components:
  - source:
      type: git
      url: https://github.com/strange-v/ha_deck
      ref: main
    components: [ hd_device_sc01_plus, ha_deck ]

# Screen
#output:
#  - platform: ledc
#    pin: 10
#    id: out_10

hd_device_sc01_plus:
  id: device
  brightness: 100

ha_deck:
  id: deck
  main_screen: ${screen_main}
  inactivity:
    period: 60
    blank_screen: true
  on_inactivity_change:
    lambda:  |-
      if (x) {
        id(device).set_brightness(id(inactive_screen_brightness).state);
      } else {
        id(device).set_brightness(id(screen_brightness).state);
      }
