# Designed for Xiao C3
esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf

# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}

# Over the Air Updates
ota:
- platform: esphome

# Enable Home Assistant API
api:

# Enable logging
logger:
