# Designed for Seeedstudio Xiao C3
esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: arduino

# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}

# Over the Air Updates
ota:
- platform: esphome

# Enable Home Assistant API
api:

# Enable logging
logger:
